name:                dictator

ghc-options: -O -threaded -Wall

dependencies:
  - base >= 4.14 && < 5
  - relude

  - aeson
  - authenticate-oauth
  - base64
  - bytestring
  - colour
  - containers
  - data-default
  - discord-haskell
  - hedis
  - hint
  - http-client
  - lens
  - lens-aeson
  - MonadRandom
  - mtl
  - multiset
  - normaldistribution
  - palette
  - parsec
  - random-shuffle
  - random
  - safe
  - scientific
  - string-interpolate
  - text
  - time
  - twitter-conduit
  - typed-process
  - unliftio
  - wreq
  - zip

executable:
  source-dirs: src
  main: Main.hs
